using latest pycryptodome version
capless/python-jose-cryptodome pull request #7
Opened 2019-01-23 02:39 UTC by ricokareem

https://nvd.nist.gov/vuln/detail/CVE-2018-15560
PyCryptodome before 3.6.6 has an integer overflow in the data_len variable in AESNI.c, related to the AESNI_encrypt and AESNI_decrypt functions, leading to the mishandling of messages shorter than 16 bytes.

<img width="776" alt="screen shot 2019-01-22 at 6 38 37 pm" src="https://user-images.githubusercontent.com/128533/51579210-f7909c80-1e74-11e9-90db-46735d790aed.png">

2019-05-30 10:46 UTC, diraven commented
It would be really nice to have this accepted.

2019-09-17 00:56 UTC, cackovic commented
Agreed. Can we please release this?

2019-10-08 17:30 UTC, rcpeters commented
Any updates...?

2019-12-11 15:53 UTC, mgrazebrook requested changes
7.9.4 or 7.9.5a by now ...

2019-12-11 22:40 UTC, ricokareem commented
updated -- https://github.com/capless/python-jose-cryptodome/pull/9

2019-12-11 22:40 UTC, closed without merging

2019-12-12 22:54 UTC, mgrazebrook commented
Thank you